services:
  postgres-db:
    image: 'postgres:alpine'
    ports:
      - '5432:5432'
    volumes:
      - ./volumes:/var/data/postgres
    environment:
      - POSTGRES_DB=${PG_DB_NAME}
      - POSTGRES_USER=${PG_DB_USER}
      - POSTGRES_PASSWORD=${PG_DB_PASSWORD}